# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: USER-WINDOWS

on: 
  push:
    paths:
      - src/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  USER:
    runs-on: windows-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
      - uses: actions/checkout@v6
      - name: Test install
        run: make
      - name: Test download
        run: |
            "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "mp4" | bin/get-yt.exe
            "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "m4a" | bin/get-yt.exe