# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: INSTALL

on: 
  push:
    paths: src/**
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  USER:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
          cache-dependency-path: go.work
      - uses: actions/checkout@v4
      - name: Test install
        run: sudo curl -fsSL https://github.com/yuki-bara/get-yt/raw/refs/heads/main/installation/auto_install.bash | bash
      - name: Test download
        run: get-yt -mp4 https://www.youtube.com/watch?v=dQw4w9WgXcQ